### PR TITLE
Updating seed

### LINKED ISSUE #6: Update the seed
The seed has evolved a lot... we could update this repo applying the seed improvements to be a better learning place.

### PR DESCRIPTION
**Pull request by Bigous**
Lots of changes has been done to the seed.
Resolves #6

### CODE REVIEW

**Comment by Bigous** [comment]
@NathanWalker or @mgechev could you review/merge?

**Comment by mgechev** [comment]
I'll take a look in an hour or two.

**Comment by mgechev** [comment]
LGTM

**Comment by Bigous** [comment]
tks :)

**Pull request merged**
